// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'line_item.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

LineItem _$LineItemFromJson(Map<String, dynamic> json) => LineItem(
  id: json['id'] as String,
  cartId: json['cartId'] as String?,
  orderId: json['orderId'] as String?,
  swapId: json['swapId'] as String?,
  claimOrderId: json['claimOrderId'] as String?,
  variantId: json['variantId'] as String?,
  title: json['title'] as String,
  description: json['description'] as String?,
  thumbnail: json['thumbnail'] as String?,
  isReturn: json['isReturn'] as bool? ?? false,
  requiresShipping: json['requiresShipping'] as bool? ?? true,
  quantity: (json['quantity'] as num).toInt(),
  fulfilledQuantity: (json['fulfilledQuantity'] as num?)?.toInt(),
  returnedQuantity: (json['returnedQuantity'] as num?)?.toInt(),
  shippedQuantity: (json['shippedQuantity'] as num?)?.toInt(),
  unitPrice: (json['unitPrice'] as num).toInt(),
  taxIncludedInPrice: json['taxIncludedInPrice'] as bool?,
  total: (json['total'] as num).toInt(),
  subtotal: (json['subtotal'] as num).toInt(),
  taxTotal: (json['taxTotal'] as num).toInt(),
  discountTotal: (json['discountTotal'] as num).toInt(),
  giftCardTotal: (json['giftCardTotal'] as num).toInt(),
  originalTotal: (json['originalTotal'] as num).toInt(),
  originalTaxTotal: (json['originalTaxTotal'] as num).toInt(),
  originalItemTotal: (json['originalItemTotal'] as num).toInt(),
  originalItemSubtotal: (json['originalItemSubtotal'] as num).toInt(),
  originalItemTaxTotal: (json['originalItemTaxTotal'] as num).toInt(),
  originalItemDiscountTotal: (json['originalItemDiscountTotal'] as num).toInt(),
  originalItemGiftCardTotal: (json['originalItemGiftCardTotal'] as num).toInt(),
  metadata: json['metadata'] as Map<String, dynamic>?,
  createdAt: DateTime.parse(json['createdAt'] as String),
  updatedAt: DateTime.parse(json['updatedAt'] as String),
);

Map<String, dynamic> _$LineItemToJson(LineItem instance) => <String, dynamic>{
  'id': instance.id,
  'cartId': instance.cartId,
  'orderId': instance.orderId,
  'swapId': instance.swapId,
  'claimOrderId': instance.claimOrderId,
  'variantId': instance.variantId,
  'title': instance.title,
  'description': instance.description,
  'thumbnail': instance.thumbnail,
  'isReturn': instance.isReturn,
  'requiresShipping': instance.requiresShipping,
  'quantity': instance.quantity,
  'fulfilledQuantity': instance.fulfilledQuantity,
  'returnedQuantity': instance.returnedQuantity,
  'shippedQuantity': instance.shippedQuantity,
  'unitPrice': instance.unitPrice,
  'taxIncludedInPrice': instance.taxIncludedInPrice,
  'total': instance.total,
  'subtotal': instance.subtotal,
  'taxTotal': instance.taxTotal,
  'discountTotal': instance.discountTotal,
  'giftCardTotal': instance.giftCardTotal,
  'originalTotal': instance.originalTotal,
  'originalTaxTotal': instance.originalTaxTotal,
  'originalItemTotal': instance.originalItemTotal,
  'originalItemSubtotal': instance.originalItemSubtotal,
  'originalItemTaxTotal': instance.originalItemTaxTotal,
  'originalItemDiscountTotal': instance.originalItemDiscountTotal,
  'originalItemGiftCardTotal': instance.originalItemGiftCardTotal,
  'metadata': instance.metadata,
  'createdAt': instance.createdAt.toIso8601String(),
  'updatedAt': instance.updatedAt.toIso8601String(),
};
